name:          KrishaWeb Engineering Best Practices
title:         KrishaWeb Engineering Best Practices
description:   Engineering best practices used by KrishaWeb.
url:           https://praful-kwt.github.io/
baseurl:       /Engineering-Best-Practices
author:
  name:    KrishaWeb
  email:   sales@KrishaWeb.com
  github:  KrishaWeb
  twitter: KrishaWeb

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass
